version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@4.7.0
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - node/test:
          app-dir: ~/project/backend
      - eb/deploy:
          app-dir: ~/project/backend
          context: aws-creds-2
          application-name: Restranteb01-env.eba-rjyvbxxm.us-east-1.elasticbeanstalk.com
          environment-name: rest-rant-eb-01
          filters:
            branches:
              only:
                - main
          label: version-<<pipeline.number>>
